basePath: /api/v1
definitions:
  handler.SavePositionRequest:
    properties:
      latitude:
        maximum: 90
        minimum: -90
        type: number
      longitude:
        maximum: 180
        minimum: -180
        type: number
      user_id:
        type: string
    required:
    - latitude
    - longitude
    - user_id
    type: object
  usecase.CreateUserRequest:
    properties:
      email:
        type: string
      event_id:
        type: string
      id:
        type: string
      name:
        type: string
    required:
    - email
    - event_id
    - id
    - name
    type: object
  usecase.CreateUserResponse:
    properties:
      email:
        type: string
      event_id:
        type: string
      message:
        type: string
      name:
        type: string
      user_id:
        type: string
    type: object
  usecase.FindNearbyUsersResponse:
    properties:
      message:
        type: string
      nearby_users:
        items:
          $ref: '#/definitions/usecase.NearbyUserResponse'
        type: array
      search_center:
        $ref: '#/definitions/usecase.NearbyUserResponse'
      total_found:
        type: integer
    type: object
  usecase.GetCurrentPositionResponse:
    properties:
      age:
        type: string
      latitude:
        type: number
      longitude:
        type: number
      message:
        type: string
      position_id:
        type: string
      sector_id:
        type: string
      user_id:
        type: string
      user_name:
        type: string
    type: object
  usecase.GetPositionHistoryResponse:
    properties:
      history:
        items:
          $ref: '#/definitions/usecase.PositionHistoryItem'
        type: array
      message:
        type: string
      total:
        type: integer
      user_id:
        type: string
      user_name:
        type: string
    type: object
  usecase.GetUsersInSectorResponse:
    properties:
      message:
        type: string
      requested_by:
        $ref: '#/definitions/usecase.SectorUserResponse'
      sector_bounds:
        $ref: '#/definitions/usecase.SectorBounds'
      sector_id:
        type: string
      total_found:
        type: integer
      users_in_sector:
        items:
          $ref: '#/definitions/usecase.SectorUserResponse'
        type: array
    type: object
  usecase.NearbyUserResponse:
    properties:
      age:
        description: 'Ex: "5m30s"'
        type: string
      distance_meters:
        type: number
      latitude:
        type: number
      longitude:
        type: number
      position_id:
        type: string
      sector_id:
        type: string
      user_id:
        type: string
      user_name:
        type: string
    type: object
  usecase.PositionHistoryItem:
    properties:
      age:
        type: string
      latitude:
        type: number
      longitude:
        type: number
      position_id:
        type: string
      recorded_at:
        type: string
      sector_id:
        type: string
    type: object
  usecase.SaveUserPositionResponse:
    properties:
      message:
        type: string
      position_id:
        type: string
      sector_id:
        type: string
    type: object
  usecase.SectorBounds:
    properties:
      max_latitude:
        type: number
      max_longitude:
        type: number
      min_latitude:
        type: number
      min_longitude:
        type: number
    type: object
  usecase.SectorUserResponse:
    properties:
      age:
        description: 'Ex: "5m30s"'
        type: string
      latitude:
        type: number
      longitude:
        type: number
      position_id:
        type: string
      user_id:
        type: string
      user_name:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@example.com
    name: API Support
    url: http://www.example.com/support
  description: |-
    API para rastreamento de geolocalização de usuários em eventos
    Esta API permite criar usuários, salvar posições geográficas e consultar usuários próximos
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Geolocation Tracker API
  version: "1.0"
paths:
  /positions:
    post:
      consumes:
      - application/json
      description: Salva uma nova posição geográfica para um usuário específico
      parameters:
      - description: Dados da posição
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.SavePositionRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Posição salva com sucesso
          schema:
            $ref: '#/definitions/usecase.SaveUserPositionResponse'
        "400":
          description: Dados de posição inválidos
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Usuário não encontrado
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Erro interno do servidor
          schema:
            additionalProperties: true
            type: object
      summary: Salvar posição do usuário
      tags:
      - positions
  /positions/nearby:
    get:
      consumes:
      - application/json
      description: Busca usuários próximos a uma coordenada específica dentro de um
        raio determinado
      parameters:
      - description: ID do usuário que está buscando
        in: query
        name: user_id
        required: true
        type: string
      - description: Latitude da posição de referência (-90 a 90)
        in: query
        name: latitude
        required: true
        type: number
      - description: Longitude da posição de referência (-180 a 180)
        in: query
        name: longitude
        required: true
        type: number
      - description: Raio de busca em metros (1 a 50000)
        in: query
        name: radius_meters
        required: true
        type: number
      - description: 'Número máximo de resultados (padrão: 50)'
        in: query
        name: max_results
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Lista de usuários próximos
          schema:
            $ref: '#/definitions/usecase.FindNearbyUsersResponse'
        "400":
          description: Parâmetros de busca inválidos
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Erro interno do servidor
          schema:
            additionalProperties: true
            type: object
      summary: Buscar usuários próximos
      tags:
      - positions
  /positions/sector:
    get:
      consumes:
      - application/json
      description: Busca todos os usuários que estão no mesmo setor geográfico de
        uma coordenada específica
      parameters:
      - description: ID do usuário que está buscando
        in: query
        name: user_id
        required: true
        type: string
      - description: Latitude da posição de referência (-90 a 90)
        in: query
        name: latitude
        required: true
        type: number
      - description: Longitude da posição de referência (-180 a 180)
        in: query
        name: longitude
        required: true
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: Lista de usuários no setor
          schema:
            $ref: '#/definitions/usecase.GetUsersInSectorResponse'
        "400":
          description: Parâmetros de busca inválidos
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Erro interno do servidor
          schema:
            additionalProperties: true
            type: object
      summary: Buscar usuários no mesmo setor
      tags:
      - positions
  /users:
    post:
      consumes:
      - application/json
      description: Cria um novo usuário no sistema para participar de um evento
      parameters:
      - description: Dados do usuário
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/usecase.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Usuário criado com sucesso
          schema:
            $ref: '#/definitions/usecase.CreateUserResponse'
        "400":
          description: Erro de validação
          schema:
            additionalProperties: true
            type: object
        "409":
          description: Usuário já existe
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Erro interno do servidor
          schema:
            additionalProperties: true
            type: object
      summary: Criar um novo usuário
      tags:
      - users
  /users/{id}/position:
    get:
      consumes:
      - application/json
      description: Retorna a posição geográfica atual de um usuário específico
      parameters:
      - description: ID do usuário
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Posição atual do usuário
          schema:
            $ref: '#/definitions/usecase.GetCurrentPositionResponse'
        "400":
          description: ID do usuário inválido
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Usuário não encontrado
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Erro interno do servidor
          schema:
            additionalProperties: true
            type: object
      summary: Obter posição atual do usuário
      tags:
      - users
  /users/{id}/positions/history:
    get:
      consumes:
      - application/json
      description: Retorna o histórico de posições geográficas de um usuário com limite
        configurável
      parameters:
      - description: ID do usuário
        in: path
        name: id
        required: true
        type: string
      - description: 'Número máximo de posições a retornar (padrão: 10, máximo: 100)'
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Histórico de posições do usuário
          schema:
            $ref: '#/definitions/usecase.GetPositionHistoryResponse'
        "400":
          description: ID do usuário inválido
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Usuário não encontrado
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Erro interno do servidor
          schema:
            additionalProperties: true
            type: object
      summary: Obter histórico de posições do usuário
      tags:
      - users
schemes:
- http
- https
swagger: "2.0"
tags:
- description: Operações relacionadas a usuários
  name: users
- description: Operações relacionadas a posições geográficas
  name: positions
- description: Operações de health check
  name: health
